### PR TITLE
fixed when npm install  extract-text-webpack-plugin@beta not  found error ( #665 )

### LINKED ISSUE #665: No compatible version found: extract-text-webpack-plugin@beta
when i try `npm install`
i failed and the message:
```
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: extract-text-webpack-plugin@beta
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 1.0.0, 1.0.1, 2.0.0-beta.0, 2.0.0-beta.1, 2.0.0-beta.2, 2.0.0-beta.3, 2.0.0-beta.4, 2.0.0-beta.5, 2.0.0-rc.0, 2.0.0-rc.1, 2.0.0-rc.2, 2.0.0-rc.3, 2.0.0, 2.1.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'vue-material'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2017-04-05T09_20_26_040Z-debug.log
```

### PR DESCRIPTION
**Pull request by xinzhanguo**
fixed failed npm install

### CODE REVIEW

**Comment by xinzhanguo** [comment]
@marcosmoura

File: src/components/mdSpinner/mdSpinner.vue [hunk 1]
```diff
@@ -2,7 +2,7 @@
   <transition name="md-spinner" appear>
     <div class="md-spinner" :class="[themeClass, classes]":style="styles">
       <svg class="md-spinner-draw" viewBox="25 25 50 50">
-        <circle class="md-spinner-path" cx="50" cy="50" r="20" :stroke-width="mdStroke" :stroke-dasharray="dashProgress">
+        <circle class="md-spinner-path" cx="50" cy="50" r="20" :stroke-width="mdStroke" :stroke-dasharray="dashProgress" />
```
Comment (Morgul) [inline src/components/mdSpinner/mdSpinner.vue]: While this seems an appropriate fix, it's not mentioned in your PR, nor does it seem related. It is a good practice to mention all changes, even if they are minor, so the maintainer doesn't have any surprises when they merge your fixes.
